[book]
authors = ["Steven Hé (Sīchàng)"]
language = "en"
multilingual = false
src = "src"
title = "MDBook Fancy Template"
curly-quotes = true

[build]
build-dir = "."

[output.html]
no-section-label = true
git-repository-url = "https://github.com/SichangHe/mdbook_fancy_theme"

[output.html.fold]
enable = true

[output.katex]

[preprocessor.katex]
